2024-05-22 00:38:00,479 django.request ERROR    Internal Server Error: /api/gu/1
2024-05-22 00:38:00,479 django.request ERROR    Internal Server Error: /api/gu/1
2024-05-22 02:26:13,620 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 02:26:13,620 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 02:33:42,285 django.request ERROR    Internal Server Error: /api/ia
2024-05-22 02:33:42,285 django.request ERROR    Internal Server Error: /api/ia
2024-05-22 02:39:40,745 django.security.DisallowedHost ERROR    Invalid HTTP_HOST header: '89.111.175.10:3000'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '89.111.175.10:3000'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
2024-05-22 02:40:41,802 django.security.DisallowedHost ERROR    Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
2024-05-22 02:40:45,609 django.security.DisallowedHost ERROR    Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
2024-05-22 02:40:48,586 django.security.DisallowedHost ERROR    Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '89.111.175.10'. You may need to add '89.111.175.10' to ALLOWED_HOSTS.
2024-05-22 02:44:26,313 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 02:44:26,313 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 02:44:45,267 django.request ERROR    Internal Server Error: /api/f/1
2024-05-22 02:44:45,267 django.request ERROR    Internal Server Error: /api/f/1
2024-05-22 02:51:12,838 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 02:51:12,838 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:15:57,981 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:15:57,981 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:36:37,887 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:36:37,887 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:40:38,550 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 03:40:38,550 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 04:04:18,013 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 04:04:18,013 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 04:04:24,531 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 04:04:24,531 django.request ERROR    Internal Server Error: /api/gd
2024-05-22 06:17:23,013 django.request ERROR    Internal Server Error: /download/gAAAAABmTWEUZgxUnxC06EVm_b4v0uyVyo70cYKy-ovx39RtZfdKGvuZEFK8OHmwAXf1W5-ZC5nhxx09U4o7EljSdXKt4gKG8Q==
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/cloud/backend/app/views.py", line 234, in download_view
    return get_file(request, code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 391, in initialize_request
    return Request(
           ^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/request.py", line 154, in __init__
    assert isinstance(request, HttpRequest), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: The `request` argument must be an instance of `django.http.HttpRequest`, not `rest_framework.request.Request`.
2024-05-22 06:17:23,013 django.request ERROR    Internal Server Error: /download/gAAAAABmTWEUZgxUnxC06EVm_b4v0uyVyo70cYKy-ovx39RtZfdKGvuZEFK8OHmwAXf1W5-ZC5nhxx09U4o7EljSdXKt4gKG8Q==
Traceback (most recent call last):
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/cloud/backend/app/views.py", line 234, in download_view
    return get_file(request, code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/views.py", line 391, in initialize_request
    return Request(
           ^^^^^^^^
  File "/home/proj/.env/lib/python3.12/site-packages/rest_framework/request.py", line 154, in __init__
    assert isinstance(request, HttpRequest), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: The `request` argument must be an instance of `django.http.HttpRequest`, not `rest_framework.request.Request`.
